### ISSUE TITLE
I could not use your library with Arduino MKRZERO.

### ISSUE THREAD

**Issue by ScottJeong** [ubidots/ubidots-arduino-ethernet#8]
Hi, I'm Wiznet's engineer.

I used your library well with Arduino Uno.

But I could not use your library with Arduino MKRZERO.

I used two examples, but all had an error. I used the UbidotsSaveValues ​​and UbidotsGetValue examples.

I have temporarily modified your library and examples to fix the error.

- Change PORT variable name to ETH_PORT used in UbidotsEthernet.cpp and UbidotsEthernet.h
  - The Arduino board library and PORT are expected to be used.

- Problem with const variable used to call getValue, change const variable to general variable
  - AVR and ARM structure difference expected

Can I use it like this? Do you have an update plan?

I look forward to your reply.

Thank you.

**Comment by jotathebest** [comment]
Greetings Scott, thanks for writing. Answering your questions:

**Can I use it like this?**

Our libraries licenses specify that you may copy or modify the main source code, so feel free to use your actual script as always as it fits your needs.

**Do you have an update plan?**

This library is not planned to be updated in a short time as we do not usually see issues reports with it, but if the issue is just related with the port naming, it is something that for sure we may just change or, if you wish, just create a PR with the fix and we will be glad to merge it so you can be recorded as a contributor to the library.

I will be attentive to your thoughts.

Jose García
Developer @Ubidots
